<?php

  use yii\helpers\html;

?>

<div class="container">
  <div class="row">
    <div class="col-xs-10 col-xs-offset-1 text-justify">
      <h2 class="title-default">Términos y condiciones</h2>
      <i>Usar este sitio implica aceptar nuestros Términos y Condiciones de Uso. Prohibida su reproducción total o parcial, así como su traducción a cualquier idioma sin autorización escrita de su titular.</i><br><br>
      <p>
        1. Introducción.<br><br>
        Al ingresar y utilizar este portal de Internet, propiedad de Comunidad Autojal, S. de R. L., una sociedad mexicana dedicada a realizar actividades relacionadas con la promoción, publicidad y desarrollo de contenidos y artículos en relación con la industria automotriz a través de Internet, entre otras actividades, con domicilio en Calle Morelos 1520, Americana, Guadalajara, Jalisco CP 44600, mediante el sitio web www.autojal.mx, el usuario está aceptando los términos y condiciones de uso contenidos en el presente AVISO LEGAL y declara expresamente su aceptación utilizando para tal efecto este medio electrónico, en términos de lo dispuesto por el artículo 1803 del Código Civil Federal.<br><br>
        En caso de no aceptar en forma absoluta y completa los términos y condiciones de este convenio, el usuario deberá abstenerse de utilizar y acceder al sitio web www.autojal.mx <br><br>
        Y en caso de que el usuario acceda a el sitio web www.autojal.mx se considera como una aceptación de los Términos y condiciones de uso aquí señalados. <br><br>
        La sola utilización de la mencionada página de Internet le otorga al público en general la condición de usuario-cliente (en adelante referido como el usuario-cliente) e implica la aceptación, plena e incondicional, de todas y cada una de las condiciones generales y particulares incluidas en estos términos y condiciones de uso.<br><br>
        Cualquier modificación a los Términos y condiciones de uso será realizada cuando Comunidad Autojal, S. de R. L., lo considere apropiado, siendo exclusiva responsabilidad del usuario asegurarse de tomar conocimiento de tales modificaciones. <br><br>
        2. Convenio.<br><br>
        Convenio de adhesión para el uso de la página de Internet www.autojal.mx que celebran: por una parte, Comunidad Autojal, S. de R. L. y por la otra, el usuario-cliente, sujetándose, ambas partes, a lo establecido en este documento.<br><br>
        3. Licencia.<br><br>
        a) Por virtud de la celebración de este convenio, otorga y concede al usuario el derecho no exclusivo, revocable y no transferible de ver y utilizar el sitio Web www.autojal.mx de conformidad con los términos y condiciones de uso que aquí se estipulan. Para los efectos del presente convenio, las partes acuerdan que por usuario-cliente se entenderá a cualquier persona de cualquier naturaleza que ingrese al sitio web www.autojal.mx y/o a cualquiera de las subpáginas que despliegan su contenido y/o a la persona de cualquier naturaleza que se de alta y/o use cualquiera de los servicios que se ofrecen de dicha página.<br><br>
        b) El usuario solo podrá imprimir y/o copiar cualquier información contenida o publicada en el sitio web www.autojal.mx exclusivamente para uso personal, queda terminantemente prohibido el uso comercial de dicha información En caso de ser persona moral se sujetará lo dispuesto por el artículo 148, fracción IV de la Ley Federal del Derecho de Autor.
        c) La utilización, publicación, distribución, asignación, subsidencia, venta, reproducción electrónica o por otro medio, parcial o total, de cualquier información, documento o gráfico que aparezca en el sitio web www.autojal.mx para cualquier uso distinto al personal no comercial le están expresamente prohibido al usuario, a menos de que cuente con la autorización previa y por escrito de Comunidad Autojal, S. de R. L. y/o de la agencia-proveedor y/o de la Financiera, según sea el caso.<br><br>
        4. Reglas para el uso del sitio web www.autojal.mx<br><br>
        El usuario y Comunidad Autojal, S. de R. L. están de acuerdo en que la utilización del
        sitio web www.autojal.mx se sujetará a las siguientes reglas:<br><br>
        a) El usuario reconoce y acepta que la información publicada o contenida en dicho sitio será claramente identificada de forma tal que se reconozca que la misma proviene y ha sido generada por las marcas, agencias, financieras y demás proveedores. No obstante, la información, publicada en dicho sitio no necesariamente reflejan la posición de Comunidad Autojal, S. de R. L., ni de accionistas, directores, empleados y franquiciatarios (en lo sucesivo los afiliados). Por este motivo Comunidad Autojal, S. de R. L. no se hace responsable por ninguna de las informaciones, que se emitan en la página web referida. En este caso, se recomienda al usuario utilizar la información del sitio web de manera orientativa y de consulta. Asimismo, Comunidad Autojal, S. de R. L. no se hace responsable de la información contenida en la página de Internet, en el entendido de que el uso y seguimiento de esta es bajo riesgo y responsabilidad del usuario.
        Comunidad Autojal, S. de R. L. se reserva el derecho de bloquear el acceso o remover en forma parcial o total toda información, comunicación o material que a su exclusivo juicio pueda resultar:<br><br>
        i. Fraudulento, abusivo, o engañoso.<br>
        ii. Violatorio de derechos de autor, marcas, confidencialidad, secretos<br>
        industriales o cualquier derecho de propiedad intelectual de un tercero.<br>
        iii. Ofensivo.<br>
        iv. Que de cualquier forma contravenga lo establecido en este convenio.<br><br>
        b) El usuario reconoce que la información de los anuncios publicados puede cambiar cuando la ve y la usa, por lo que se recomienda verificar el contenido en la misma, tales como: precio, características, observaciones, etc., con el vendedor directo.<br><br>
        c) El usuario reconoce que el contenido de la ficha técnica, precios, observaciones, etc., del sitio web es informativo y referencial, los cuales pueden cambiar en cualquier momento, por lo que se recomienda verificar la información directamente con la agencia-proveedor.
        El usuario reconoce que Comunidad Autojal, S. de R. L. no controla o censura previamente el contenido disponible en la página de Internet.<br><br>
        d) Todos los anuncios, publicaciones, opiniones, declaraciones, servicios, ofertas, fotografías u otras informaciones o contenidos expresados o puestos a disposición del público por terceros pertenecen a su respectivo autor y Comunidad Autojal, S. de R. L.no asume responsabilidad alguna frente a ello. De la misma forma,Comunidad Autojal, S. de R. L.no garantiza la exactitud, veracidad, amplitud y/o utilidad de cualquier contenido provisto por tales terceros. Comunidad Autojal, S. de R. L. no es responsable ni garantiza la exactitud, exhaustividad, veracidad y/o confiabilidad de cualquier anuncio, publicación, opinión, declaración, servicio, oferta y fotografías publicados por los usuarios a través de la página de Internet www.autojal.mx y bajo ninguna circunstancia Comunidad Autojal, S. de R. L. será responsable de cualquier daño y/o perjuicio, directo o indirecto, causado en virtud de la confianza que el usuario deposite en información obtenida a través de su sitio web. <br><br>
        5. Derechos de autor y propiedad industrial<br><br>
        Comunidad Autojal, S. de R. L. y el sitio Web www.autojal.mx sus logotipos y todo el material que aparece en dicho sitio son marcas, nombres de dominio, nombres comerciales y obras artísticas propiedad de sus respectivos titulares y están protegidos por tratados internacionales y las leyes aplicables en materia de propiedad intelectual y derechos de autor en México.<br><br>
        6. Material publicitario.<br><br>
        El usuario reconoce y acepta que Comunidad Autojal, S. de R. L. es una organización independiente de terceros patrocinadores y anunciantes cuya información, imágenes, anuncios y demás, fotografías, material publicitario o promocional (en lo subsecuente material publicitario) puede ser publicado en el sitio web www.autojal.mx<br><br>
        7. Garantías.<br><br>
        El usuario está de acuerdo que la utilización del sitio web www.autojal.mx se realiza bajo su propio riesgo y que los servicios y productos que ahí se prestan y ofrecen se prevén sobre una base tal cual y según sean disponibles. Comunidad Autojal, S. de R. L. no garantiza que la página satisfaga los requerimientos del usuario o que los servicios que en ella se ofrecen no sufran interrupciones, sean seguros o estén exentos de errores.
        Comunidad Autojal, S. de R. L. no garantiza o avala en ninguna forma la veracidad, precisión, legalidad, moralidad o ninguna otra característica del contenido del material que se publique en el sitio Web www.autojal.mx
        Comunidad Autojal, S. de R. L. se libera de cualquier responsabilidad y condiciones, tanto expresas como implícitas, en relación con los servicios e información contenida o disponible en o a través de esta página web; incluyendo, sin limitación alguna:<br><br>
        a) La disponibilidad de uso del sitio web www.autojal.mx<br><br>
        b) La ausencia de virus, errores, desactivadores o cualquier otro material contaminante o con funciones destructivas en la información o programas disponibles en o a través de esta página o en general cualquier falla en dicho sitio.<br><br>
        8. Modificaciones al sitio Web www.autojal.mx<br><br>
        Comunidad Autojal, S. de R. L. podrá en cualquier momento y cuando lo considere conveniente, sin necesidad de avisar al usuario, realizar correcciones, adiciones, mejoras o modificaciones al contenido, presentación, información, servicios, bases de datos y demás elementos de dicho sitio, sin que ello de lugar ni derecho a ninguna reclamación o indemnización, ni que esto implique reconocimiento de responsabilidad alguna a favor del usuario.<br><br>
        9. Modificaciones al convenio.<br><br>
        Comunidad Autojal, S. de R. L. se reserva el derecho de modificar los términos y condiciones de uso de este convenio en cualquier momento, siendo efectivas dichas modificaciones de forma inmediata por medio de:<br><br>
        a) La publicación en el sitio web www.autojal.mx del convenio modificado o,<br><br>
        b) La notificación al usuario sobre dichas modificaciones por cualquier medio
        impreso o electrónico.<br><br>
        De esta forma, el usuario está de acuerdo en revisar dicho convenio periódicamente con la finalidad de mantenerse al tanto de dichas modificaciones. No obstante, lo anterior, cada vez que el usuario acceda al sitio se considera como una aceptación absoluta a las modificaciones del presente convenio.
        Comunidad Autojal, S. de R. L. podrá, en cualquier momento y cuando así lo estime conveniente, ceder total o parcialmente sus derechos y obligaciones derivados del presente convenio. Comunidad Autojal, S. de R. L. queda liberada de cualquier obligación a favor del usuario, establecida en el presente convenio.<br><br>
        10. Indemnización.<br><br>
        El usuario está de acuerdo en indemnizar a Comunidad Autojal, S. de R. L., sus accionistas, directores, empleados y franquiciatarios por cualquier acción, demanda o reclamación (incluso de honorarios de abogados y de costas judiciales) derivadas de cualquier incumplimiento por parte del usuario al presente convenio; incluyendo, sin limitación de alguna de las derivadas de:<br><br>
        a) Cualquier aspecto relativo al uso del sitio web www.autojal.mx<br>
        b) La información contenida o disponible en o a través de dicho sitio o de injurias, difamación, robo de información o cualquier otra conducta violatoria del presente convenio por parte del usuario en el uso de la página web señalada.<br>
        c) La violación a las leyes aplicables o tratados internacionales relativos a los derechos de autor o propiedad intelectual, contenidos o disponibles en, o a través de dicho sitio web.<br><br>
        11. Terminación.<br><br>
        Comunidad Autojal, S. de R. L. se reserva el derecho, a su exclusiva discreción, y sin necesidad de aviso o notificación al usuario, para:<br>
        a. Terminar definitivamente el presente convenio.<br>
        b. Descontinuar o dejar de publicar definitivamente el sitio web www.autojal.mx sin responsabilidad alguna para la Comunidad Autojal, S. de R. L., sus afiliados y/o agencia-proveedor.<br><br>
        12. Cancelaciones y Devoluciones de Pagos.<br><br>
        Comunidad Autojal, S. de R. L. para el caso de dar por terminado definitivamente el presente convenio, descontinuar o dejar de publicar definitivamente una publicación dentro del sitio web www.autojal.mx devolverá el pago de la publicación a la agencia-proveedor, en caso de existir, si se detectará un caso de sospecha de fraude o previa aclaración administrativa enviada a contacto@autojal.mx<br><br>
        13. No renuncia de derechos.<br><br>
        La inactividad por parte de Comunidad Autojal, S. de R. L., afiliados, proveedores al ejercicio de cualquier derecho o acción derivados del presente convenio, en ningún momento deberá interpretarse como renuncia a dichos derechos o acciones.<br><br>
        14. Legislación aplicable y jurisdicción.<br><br>
        Este convenio estará sujeto y ser interpretado de acuerdo con las leyes y ante los tribunales de la Ciudad de Guadalajara, Jalisco México.
        Aviso legal. “Plataforma Autojal”.<br><br>
        INTRODUCCIÓN<br>
        La Aplicación Web, denominada “Plataforma Autojal”, brinda el servicio de localización, ubicación y promoción de Autos Nuevos y Seminuevos, con las agencias-proveedores conveniados con la plataforma, para facilitar la compra y venta de dichos productos. Al reservar un vehículo con la PLATAFORMA AUTOJAL, el “Usuario-Cliente” acepta las condiciones que se establecen a continuación, manifestando su total conformidad con éstas, por lo que solicitamos leer con detención los términos y condiciones que rigen la prestación del servicio. El presente instrumento regula la prestación del servicio de apartado de autos nuevos y seminuevos, por la PLATAFORMA AUTOJAL, servicio ofrecido por Comunidad Autojal, S. de R. L., y mismo que es ofertado a través de su página de Internet www.autojal.mx, las unidades ofertadas en la PLATAFORMA AUTOJAL son propiedad de las agencias-proveedores externos, quienes se encargaran de confirmar las existencias y realizar los apartados definitivos para la compra de unidades.<br><br>
        TERMINOLOGIA. PLATAFORMA AUTOJAL.<br>
        Para efectos del presente AVISO LEGAL, se entiende a la aplicación web y app soportadas en la página de internet de Comunidad Autojal, S. de R. L. www.autojal.mx, la cual permite a los usuarios-clientes localizar y reservar unidades Nuevas, previa confirmación de las marcas inscritas en la plataforma, así como, encontrar, conocer y reservar las unidades seminuevas promocionadas en la página, ofertadas por una agencia-proveedor.
        USUARIO-CLIENTE. Es aquella persona física o moral que ingresa a la PLATAFORMA AUTOJAL, con el fin de conocer las opciones de compra de autos nuevos y seminuevos ofertados por las diferentes marcas automotrices y en su caso, ubicar y reservar la opción que le convenga.
        AGENCIA PROVEEDOR. Son las agencias automotrices conveniadas con Comunidad Autojal, S. de R. L. y que representan las distintas marcas comercializadas en la República Mexicana, con el fin de publicitar sus unidades en la PLATAFORMA AUTOJAL.
        APARTADOS. Se entiende por apartado de unidades nuevas y seminuevas, la cantidad que se deposita en la PLATAFORMA AUTOJAL, con la finalidad de reservar una unidad nueva o seminueva a una agencia-proveedor afiliado a la plataforma.<br><br>
        1. Objeto de los presentes términos.
        La PLATAFORMA AUTOJAL ofrece a los Usuarios-clientes una plataforma digital de reserva de unidades, propiedad de las agencias-proveedores externos. En ese sentido,la PLATAFORMA AUTOJAL pone a disposición de los usuarios la opción de ubicar, confirmar existencias y reservar de unidades nuevas y seminuevas directamente de agencias- proveedores, mediante la interacción de estas, confirmando la disponibilidad de inventarios para surtir los pedidos realizados.
        La PLATAFORMA AUTOJAL realiza, de manera limitativa, las siguientes acciones:
        (I)
        (II) (III)
        (IV)
        Ofertar en su plataforma digital, mediante su página de internet www.autojal.mx la opción de reservar un auto nuevo o seminuevo mismo que es provisto por las agencias-proveedores externos, quienes confirmarán la reserva. Por ningún motivo se debe considerar que exista algún contrato o convenio formal entre cliente y Comunidad Autojal, S. de R. L. y/o sus agencias-proveedores por el hecho de apartar una unidad y lanzar la búsqueda de confirmación. Hasta que una agencia haya confirmado la existencia de la unidad y el cliente haya acudido a la agencia con la documentación necesaria para formalizar el pedido, se podrá contemplar la formalidad del pedido.
        Facilita el acceso a una plataforma que permite confirmar las existencias de marcas, versiones, colores y modelos de autos nuevos y seminuevos propiedad de agencias-proveedores externos para la compra de vehículos.
        Permite el uso de la aplicación para realizar pagos y apartar unidades nuevas y seminuevas, sin que en este proceso implique vínculo alguno con Comunidad Autojal, S. de R. L. considerando que la PLATAFORMA AUTOJAL es exclusivamente una plataforma que vincula usuario-cliente con agencia- proveedor para la compra de unidades nuevas y seminuevas.
        Concluido el apartado y confirmación de la reserva de un auto nuevo o seminuevo por parte de la agencia-proveedor, la PLATAFORMA AUTOJAL pondrá a disposición del usuario los datos de la agencia-proveedor que cuenta con la unidad para culminar con el proceso de compra del auto en cuestión directamente en las instalaciones de esta, o bien, continuando con el proceso vía digital, mediante la intervención de un ejecutivo que la agencia-proveedor designe.
        Al aceptar vende directamente unidades. Sino que facilita a los usuarios-clientes la compra de unidades nuevas y seminuevas y lo conecta con la agencia-proveedor externos que cuentan con ellas.
        En caso de que surjan reclamaciones derivadas del proceso de compra o de las unidades nuevas o seminuevas adquiridas, dicha reclamación y/o exigencia de garantía deberá realizarse directamente con las agencias-proveedores, quienes tienen la obligación respetar las garantías aplicables y de atender las posibles controversias.<br><br>
        2.- Tarifas y cancelaciones.
        La agencia-proveedor y el usuario-cliente, podrán cancelar un pedido con unidad reservada en cualquier momento, bajo las siguientes premisas:<br><br>
        I. Los apartados solicitados para reservar un auto nuevo o seminuevo pueden variar de manera periódica de acuerdo con las políticas y/o acuerdos con las agencias-proveedores y sin previo aviso por parte de la PLATAFORMA AUTOJAL, estas y sus cargos, podrán ser revisados con un ejecutivo de la empresa Comunidad Autojal, S. de R. L.<br><br>
        II. La PLATAFORMA AUTOJAL, otorga un plazo máximo de 72 horas de realizada la solicitud de reserva de unidades nuevas y seminuevas para cancelar esta mediante un aviso al correo electrónico devoluciones@autojal.mx, con lo cual tendrá derecho a un reembolso sin penalizaciones. En caso de cancelar en un plazo superior al establecido y si se ha generado un gasto por parte de la agencia-proveedor por el traslado de unidades nuevas o seminuevas y/o algún otro concepto en perjuicio de esta, se podrá penalizar al usuario-cliente
        estos términos y condiciones, usted acepta que la PLATAFORMA AUTOJAL no
        haciendo llegar a este un informe de los costos que implicó dicho gasto por parte de la agencia-proveedor. De no haberse realizado ningún gasto en perjuicio de la agencia-proveedor se realizará la devolución del monto cancelado.<br><br>
        III. La agencia-proveedor, podrá cancelar la reserva de la unidad, en casos de fuerza mayor, considerándose estos, aquellas situaciones generadas por causas ajenas a la agencia-proveedor y que imposibiliten la entrega de la unidad. Se deberá enviar un informe al cliente con el motivo de la cancelación y presentar alternativas para la compra de su unidad. En estos casos, la devolución para el usuario-cliente, siempre será sin penalización alguna.
        La PLATAFORMA AUTOJAL, se reserva el derecho a no realizar la reserva solicitada, caso en el cual reembolsará el monto total cancelado.<br><br>
        3.- Proceso de reserva de unidades nuevas y seminuevas.
        El cliente seleccionará las características de su unidad Nueva (marca, modelo, versión, año, color, etc.), posteriormente, deberá generar un número de usuario con su información a fin de contar con sus datos para la reserva de la unidad, con esto podrá realizar el pago de un apartado de la una unidad nueva o seminueva que es de su interés. La PLATAFORMA AUTOJAL el “activará” un botón para confirmar la existencia de su unidad, el cual lanzará un mensaje simultaneo a las agencias de la marca correspondiente a la unidad solicitada (en el caso de autos seminuevos y autos demo en venta, el mensaje de confirmación de existencia se enviará específicamente a la agencia que cuenta con la unidad seleccionada), con lo cual las agencias tendrán la oportunidad, de confirmar su disponibilidad capturando el número de serie de la unidad que se asignaría al usuario-cliente, con lo cual quedará formalmente confirmada la reserva de unidad con esta agencia-proveedor.<br><br>
        4.- Cancelaciones de Reserva de unidades.
        El proveedor-agencia y el usuario-cliente, podrán cancelar un pedido con unidad reservada en cualquier momento, bajo las premisas especificadas en la cláusula 2 del presente aviso legal para la PLATAFORMA AUTOJAL.<br><br>
        5.- Obligaciones del Usuario.
        El usuario-cliente acepta que los recursos utilizados para el apartado y compra de las unidades publicadas propiedad de las agencias-proveedores, son de procedencia lícita.
        El usuario-cliente deberá presentar la documentación oficial requerida por la agencia- proveedor, con el fin de validar su información personal para la facturación y entrega de su unidad.
        El usuario-cliente deberá liquidar la unidad nueva o seminueva directamente en la agencia.
        El usuario-cliente al utilizar la PLATAFORMA AUTOJALautoriza el uso de datos confidenciales, para la realización de la compra del auto nuevo o seminuevo que está realizando con la financiera, agencia-proveedor y demás instancias que intervengan en la compra de su auto.
        El usuario-cliente conoce que deberá firmar en la agencia-proveedor el aviso de privacidad, ley antilavado, y demás documentos necesarios para la compra de su unidad y que la agencia-proveedor requieran.<br><br>
        5.- Límite de Responsabilidad.
        La PLATAFORMA AUTOJAL, no será responsable por los efectos de cualquier contrato o convención suscrito entre el usuario-cliente y agencia-proveedores externos.
        Estos términos y condiciones sobrevivirán a la expiración o terminación de este acuerdo.<br><br>
        6.- Propiedad Intelectual.
        Todos los Derechos de Propiedad Intelectual en los servicios de la PLATAFORMA AUTOJAL son propiedad de Comunidad Autojal, S. DE R. L. y no hay cesión de estos a usted por los servicios contratados. A los efectos de esta cláusula, se entenderá por "Derechos de propiedad intelectual" todos los derechos presentes y futuros de derechos de autor, marcas, diseños, patentes, semiconductores o diseños de circuito, procedimientos, técnicas y en general cualquier información que la PLATAFORMA AUTOJAL defina como confidencial, con independencia de que estos se encuentren registrados o no.
        El desarrollo, información y demás elementos entregados constituye parte la Propiedad Intelectual de la PLATAFORMA AUTOJAL por lo que queda estrictamente prohibida su reproducción, utilización, distribución y en general cualquier uso que no sea exclusivamente para los fines de los presentes términos.
        Las marcas de terceros son propiedad de sus respectivos titulares.<br><br>
        7.- Política de Privacidad y Protección de Datos Personales.
        Comunidad Autojal, S. DE R. L. se encuentra comprometida con la Privacidad y protección de los datos de sus usuarios, razón por la cual se utiliza tecnología avanzada para la protección de la información proporcionada por los Usuarios, por otra parte, cuenta con políticas y procedimientos en materia de Protección de Datos Personales acordes a la legislación mexicana vigente, razón por la cual, pone a su disposición el Aviso de Privacidad, mismo que podrá ser consultado en la siguiente liga: www.autojal.mx/avisodeprivacidad.<br><br>
        La contratación del servicio referido en los presentes términos y condiciones constituye su aceptación a nuestro Aviso de Privacidad, por lo que nos autoriza utilizar sus datos personales de conformidad con los términos de este.
        El uso de los Datos Personales Registrados en el Sitio Web tiene como única finalidad validar las órdenes de compra y mejorar la labor de información y comercialización de los productos y servicios prestados por la PLATAFORMA AUTOJAL. Dichos datos no serán traspasados a terceros, salvo personas o empresas relacionadas con Comunidad Autojal, S. DE R. L.
        Comunidad Autojal, S. DE R. L. podrá́ generar bases de datos con la información proporcionada por el usuario, las que se utilizarán por la PLATAFORMA AUTOJAL y exclusivamente para fines comerciales.
        Toda información solicitada por la PLATAFORMA AUTOJAL al Usuario, deberá́ ser proveída por éste de manera voluntaria.<br><br>
        8.- Modificación.
        Comunidad Autojal, S. DE R. L. puede en cualquier momento y sin previo aviso cambiar, actualizar y/o modificar los términos y condiciones sobre los cuales se le proporcionan los servicios de la PLATAFORMA AUTOJAL, estos términos estarán disponibles para su revisión en www.autojal.mx<br><br>
        9.- Cuentas de usuario.
        Con el fin de usar la mayor parte de los aspectos de la Plataforma Autojal, usted debe registrarse y mantener activa una cuenta personal de usuario de los Servicios (“Cuenta”). Para obtener una Cuenta debe tener como mínimo 18 años. El registro de la cuenta le requiere que comunique a Comunidad Autojal, S. de R.L. determinada información personal, como su nombre, dirección, número de teléfono móvil, entre otros datos personales, así como por lo menos un método de pago válido (bien una tarjeta de crédito o bien un socio de pago aceptado). Usted se compromete a mantener la información en su Cuenta de forma exacta, completa y actualizada. Si no mantiene la información de Cuenta de forma exacta, completa y actualizada, incluso el tener un método de pago inválido o que haya vencido, podría limitar su acceso o generar errores en los pedidos de unidades y reservas realizadas en esta plataforma. Usted es responsable de toda la actividad que ocurre en su Cuenta y se compromete a mantener en todo momento de forma segura y secreta el nombre de usuario y la contraseña de su Cuenta.<br><br>
      </p>
    </div>
  </div>
</div>
